# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/
    fetch-registry: true
    register-with-eureka: true
server:
  port: 9100
spring:
  application:
    name: auth-service
  # Redis
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: false
  jackson:
    property-naming-strategy: SNAKE_CASE
jwt:
  secret: ENC(xUS0U73UD2pMlEPt8Fi6SRtZJnZjiLburd8qo+Zm060EV1yKrF3LrzuSPoRigo1z)
