server:
  port: 9100
spring:
  application:
    name: auth-service
  config:
#    import: "optional:configserver:http://localhost:9020"
    import: "optional:configserver:http://15.165.198.76:9020"

management:
  endpoints:
    web:
      exposure:
        include: refresh
---
# Redis
spring:
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: false
