server:
  port: 9100
spring:
  profiles:
    active: local
  application:
    name: auth-service
  config:
#    import: "optional:configserver:http://localhost:9020"
    import: "optional:configserver:http://13.125.196.101:9020"

management:
  endpoints:
    web:
      exposure:
        include: refresh
