# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/
    fetch-registry: true
    register-with-eureka: true
# Redis
spring:
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: false
