# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/
    fetch-registry: true
    register-with-eureka: true
server:
  port: 9000
spring:
  application:
    name: GATEWAY-SERVICE