# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/
    fetch-registry: true
    register-with-eureka: true
server:
  port: 9000
spring:
  application:
    name: gateway-service
# Swagger
open-api:
  swagger:
    resources:
      - auth-service,/api/auth,auth-server
      - user-service,/api/user,user-server
#      - post-service./api/post,post-server

---
# Gateway
spring:
  cloud:
    gateway:
      default-filters:
        - name: SwaggerHeaderFilter
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/post/**