server:
  port: 9000
spring:
  profiles:
    active: local
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  config:
#    import: "optional:configserver:http://localhost:9020"
    import: "optional:configserver:http://13.125.196.101:9020"

management:
  endpoints:
    web:
      exposure:
        include: refresh

# Swagger
open-api:
  swagger:
    resources:
      - auth-service,/api/auth,auth-server
      - user-service,/api/user,user-server
      - post-service,/api/post,post-server
      - feed-service,/api/feed,feed-server

---
# Gateway
spring:
  cloud:
    gateway:
      default-filters:
        - name: SwaggerGatewayFilter
      routes:
        - id: auth-service-logout
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth
            - Method=DELETE
          filters:
            - AuthorizationGatewayFilter
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: user-service-signup
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user,/api/user/login,/api/user/email,/api/user/account
            - Method=POST
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
          filters:
            - AuthorizationGatewayFilter
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/post/**
          filters:
            - AuthorizationGatewayFilter
        - id: feed-service
          uri: lb://FEED-SERVICE
          predicates:
            - Path=/api/feed/**
          filters:
            - AuthorizationGatewayFilter
