# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/
    fetch-registry: true
    register-with-eureka: true
server:
  port: 9000
spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
# Swagger
open-api:
  swagger:
    resources:
      - auth-service,/api/auth,auth-server
      - user-service,/api/user,user-server
#      - post-service./api/post,post-server
jwt:
  secret: ENC(xUS0U73UD2pMlEPt8Fi6SRtZJnZjiLburd8qo+Zm060EV1yKrF3LrzuSPoRigo1z)

---
# Gateway
spring:
  cloud:
    gateway:
      default-filters:
        - name: SwaggerGatewayFilter
      routes:
        - id: auth-service-logout
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth
            - Method=DELETE
          filters:
            - AuthorizationGatewayFilter
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: user-service-signup
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user,/api/user/login
            - Method=POST
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
          filters:
            - AuthorizationGatewayFilter
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/post/**