server:
  port: 9140
spring:
  profiles:
    active: local
  application:
    name: search-service
  config:
    import: "optional:configserver:http://13.125.196.101:9020"

management:
  endpoints:
    web:
      exposure:
        include: refresh
