server:
  port: 9140
spring:
  profiles:
    active: local
  application:
    name: search-service
  config:
    import: "optional:configserver:http://13.125.196.101:9020"
  kafka:
    consumer:
      properties:
        spring:
          json:
            type:
              mapping: user:dev.ncns.sns.search.dto.kafka.UserConsumerRequestDto,
                hashtag:dev.ncns.sns.search.dto.kafka.PostHashtagRequestDto,
                updateHashtag:dev.ncns.sns.search.dto.kafka.UpdatePostHashtagRequestDto

management:
  endpoints:
    web:
      exposure:
        include: refresh
