# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/
#      defaultZone: http://15.165.198.76:9010/eureka/
    fetch-registry: true
    register-with-eureka: true
server:
  port: 9110
spring:
  application:
    name: user-service
  jackson:
    property-naming-strategy: SNAKE_CASE
