# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/
    fetch-registry: true
    register-with-eureka: true
spring:
  jpa:
    properties:
      hibernate:
        format_sql: false
