server:
  port: 9130
spring:
  application:
    name: feed-service
  config:
#    import: "optional:configserver:http://localhost:9020"
    import: "optional:configserver:http://13.125.196.101:9020"

management:
  endpoints:
    web:
      exposure:
        include: refresh
