server:
  port: 9130
spring:
  application:
    name: feed-service
  config:
#    import: "optional:configserver:http://localhost:9020"
    import: "optional:configserver:http://13.125.196.101:9020"
  kafka:
    consumer:
      properties:
        spring:
          json:
            type:
              mapping: post:dev.ncns.sns.feed.dto.response.PostResponseDto, list:dev.ncns.sns.feed.dto.request.UpdateListRequestDto
management:
  endpoints:
    web:
      exposure:
        include: refresh
