# Eureka
eureka:
  client:
    service-url:
#      defaultZone: http://15.165.198.76:9010/eureka/
      defaultZone: http://localhost:9010/eureka/
    fetch-registry: false
    register-with-eureka: false
server:
  port: 9010
spring:
  application:
    name: eureka-service
