server:
  port: 9020
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ENC(m4sdw4bPqdLknbmecYAE02a43enTPLm6JKdP1DqS27FYnO5xjAm7hSSqK0/JJlQy2TyToNboXUQiwqdTGp+UNnzie5lVVny9i50MW7BwDqk=)
          username: {username}
          password: {password}